### ISSUE TITLE
Pizero not being started correctly by crontab

### ISSUE THREAD

**Issue by Gabrielkyne** [tech4nature/HogPi#28]
The crontab in the otherFiles is not running the hedge.py correctly for the external camera

ps -ax|grep python shows that the program is running.  The camera and leds do not reponds

However the very same code on the rpi3 does work.  This is the production code 1.00

Trials:

1. Run using sh run.sh 
Runs perfectly no flickering of LED as per expectations

COMPLETE BOOT UP
1. sleep 60 && sh /home/pi/HogPi/app/remoteCam/run.sh
To allow the system to reboot properly
result:
Video now working but LEDs flickering they do not do this when run from terminal.

SUPER COMPLETE BOOT UP

2.  sleep 120 && sh /home/pi/HogPi/app/remoteCam/run.sh

Result:
The same runs video but flickering leds

**Comment by Gabrielkyne** [comment]
Systemd service test.

Results: works but still get flickering of LED lights

systemd details:

1. Create file
sudo nano /lib/systemd/system/pizero.service

2. copy info in

[Unit]
Description=My Script Service
After=multi-user.target

[Service]
Type=idle
ExecStart=/usr/bin/python3 /home/pi/HogPi/app/remoteCam/hedge.py

[Install]
WantedBy=multi-user.target


3. In order to store the script’s text output in a log file you can change the ExecStart line to :

ExecStart=/usr/bin/python3 /home/pi//HogPi/app/remoteCam/myscript.py > /home/pi/myscript.log 2>&1


4. Now the unit file has been defined we can tell systemd to start it during the boot sequence :

sudo systemctl daemon-reload
sudo systemctl enable pizero.service


5. You can check the status of your service using :

sudo systemctl status pizero.service

**Comment by sebbacon** [comment]
To clarify the problem:

1. The pizero is booting, and apparently `hedge.py` is running following boot, but no video is being recorded.
2. If you put in a delay, video is recorded but with flickering LEDs

Correct?

Can I clarify what the LEDs are expected to do?

More debugging steps:

1. I would stick with the `systemd` approach. This is in line with more standard ways of doing things.
2. Can you delete the existing `hedge.log` file, reboot, then:
3. Paste the output of `sudo systemctl status pizero.service` here (you can do this by redirecting its output to a file and then uploading the file, thus: `sudo systemctl status pizero.service > /tmp/pizero.log` (then upload `pizero.log`)
4. Also upload a copy of `hedge.log` to this issue, following some time when you would expect video to have worked

**Comment by Gabrielkyne** [comment]
4. nohup sh run.sh
records video and leds do not flicker
a temporary fix

**Comment by Gabrielkyne** [comment]
Yes summary correct the flickering of LEDs is what we are left with when we
use systemd or a larger set up times with crontabs.

Yes will initiate log and run.

nohup works fine
==========================================================================
ummm just thinking what I should do is run a check through project
initialising all gpio at 2mins
then @ 5mins run the main program
This seems a GPIO setup problem?
===========================================================================

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Gabrielkyne** [comment]
5. 500 s delay crontab
result: working flickering LED

**Comment by Gabrielkyne** [comment]
6. 
a.created a cron job to run the system through after 30s 
b.created second cron job at 300s to run program

result:
Worked but flickering LED

**Comment by Gabrielkyne** [comment]
conclusion : 
program run through cron or systemd = working + flickering LED
no setup of system helps
nohup: works
terminal: works
I HAVE NOT GOT THE FAINTEST....BUT THAT IS THE PROBLEM DEFINED
Seb suggests using systemd logging function to see if we can get more detail.

**Comment by sebbacon** [comment]
Less systemd logs (though useful for completeness), more the `hedge.log`.

I can think of no reason why this might possibly be the case.

What is the function of the LED and how is it wired in relation to the video?

**Comment by neiljw1** [comment]
Have you tried it with only one LED ? Flickering LEDs are normally a power issue. Only 1 inside box, no flickering. Worth a try ?

**Comment by Gabrielkyne** [comment]
test : change pwm to on/off 
result: LED flickering
no video recording at sleep 60 &&

conclusion : PWM not issue

**Comment by jw2476** [comment]
here's my crontab

@reboot sudo modprobe bcm2835-v4l2
@reboot /bin/sleep 60 && /usr/bin/python3 /home/pi/HogPi/app/remoteCam/hedge.py

Change the subprocess.run so the python and video.py are full paths:

subprocess.run(['/usr/bin/python3', '/home/pi/HogPi/app/remoteCam/video.py'])

Got several successful runs from this

**Comment by Gabrielkyne** [comment]
Repeating now my setup is with on/off pins

result:
led solid 
pizero activating pir

teste repeated 3 times
pir test ok after these tests

FAILED

**Comment by Gabrielkyne** [comment]
Checking lights on box did not trigger pir

**Comment by Gabrielkyne** [comment]
Getting noise on pir when in box - filter removing - not triggering

**Comment by Gabrielkyne** [comment]
Confirm this works on my system after removing light interference.

Some noise occurs when in box but that is solved by the filtering.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Gabrielkyne** [comment]
Well done Jack! You are on a roll...keep timesheet
