### ISSUE TITLE
RFID and Weight timing wrong in master branch

### ISSUE THREAD

**Issue by Gabrielkyne** [tech4nature/HogPi#35]
The rfid has to read for 120s or until it has a positive read.
There should be a 60 s gap to allow creature to get into the box.

See branch rfid and weight

**Comment by jw2476** [comment]
Could you push the changes for this into the RFID and weight branch, then I will review. Please could you use all lowercase, with words separated by hyphens for branch names.

**Comment by jw2476** [comment]
@Gabrielkyne ^
